### ISSUE TITLE
Editor: weird line breaking

### ISSUE THREAD

**Issue by klimesf** [nette/web-content#175]
While editing in `editor.nette.org`, I noticed that the line breaking is broken if you use backticks at the end of the line. However

I don't know if this is Texy's or editor's issue so I reported it here.

![screen shot 2015-01-13 at 15 00 21](https://cloud.githubusercontent.com/assets/5357636/5721834/7ec377d4-9b36-11e4-8b79-75d5858e04b0.png)

You can reproduce it [using this text](https://gist.github.com/klimesf/239ed5be676e911c895d).

**Comment by milo** [comment]
Maybe due to some [CSS Change](http://forum.nette.org/cs/19431-polozit-otazku-a-dalsi-novinky-na-foru#p135281).

**Comment by JanTvrdik** [comment]
I noticed that too. My guess is Texy bug, no time to properly test it though.

**Comment by dg** [comment]
Vyřešeno nasazením jsem Texy 2.6 https://github.com/dg/texy/releases/tag/v2.6

**Comment by klimesf** [comment]
:+1:
