### ISSUE TITLE
Formulare: setValidationScope a onValidate

### ISSUE THREAD

**Issue by matej21** [nette/web-content#265]
onValidate se spusti bez ohledu na setValidationScope, zminit

**Comment by dg** [comment]
To je bug?

**Comment by matej21** [comment]
nevim, na foru uz se to resilo nekolikrat, naposledy dnes http://forum.nette.org/cs/22557-validace-formulare-pres-onvalidate-tlacitkem-se-setvalidationscope-false :)

**Comment by dg** [comment]
IMHO to správně.

**Comment by matej21** [comment]
Mno rekl bych, ze by bylo logictejsi spoustet onValidate pouze pokud neni nastavena validation scope, pripadne pokud je nastavena na dany kontejner.
Pokud je to ale ocekavane chovani, tak krom doc dopsat test ;)

**Comment by matej21** [comment]
@dg co myslis. bug nebo feature?

**Comment by matej21** [comment]
closed by #348
