### ISSUE TITLE
composer requirements (composer.json) not in sync with documentation

### ISSUE THREAD

**Issue by klepek** [nette/web-content#299]
Hi,

http://doc.nette.org/cs/2.3/requirements states that nette require PHP 5.3.1 or higher where composer.json in nette directory states that it require php 5.3.7 or higher.

Can you please fix (either in documentation or composer.json) this discrepancy?

Thank you

**Comment by pilec** [comment]
Can you make a pull request please?

**Comment by dg** [comment]
5.3.1 is correct.

**Comment by dg** [comment]
Nette 2.3 requires 5.3.1
Nette dev requires 5.4.4
Sandbox requires 5.3.7
