### ISSUE TITLE
Zapnutý debug mod na doc.nette.org

### ISSUE THREAD

**Issue by lukasojd** [nette/web-content#398]
http://awesomescreenshot.com/06a5ffgf42

- špatný příklad pro nováčky, kterým by se mělo vtloukat že debug mod na livu musí mít vypnutý... !!! 
- security problém

**Comment by Northys** [comment]
@lukasojd ty vole ty jsi na to přišel! na posobotu toho dones trošku, dáme čáru :+1:

**Comment by matej21** [comment]
no opravdu to tam je! to je do nebe volajici opomenuti! :scream:

**Comment by milo** [comment]
Je to jen statická ukázka Tracy baru. Nic z toho nelze vyčíst.

**Comment by dg** [comment]
Easter egg

**Comment by matej21** [comment]
a ted konstruktivne: za ten ~tyden, co tam je, se na to na gitteru ptalo spousta lidi, takze to opravdu mate. U pokrocilych to muze vyvolat pocit, ze to nekdo nezodpovedne nechal zapnute. U zacatecniku to muze zas vyvolat pocit, ze asi neni tak kriticke ten debug mod vypinat, kdyz je to i na nette.org. Minimalne by tam melo byt napsano, ze se jedna o demo. A ma vubec cenu to davat i jinde, nez na tracy.nette.org?

**Comment by Majkl578** [comment]
Souhlasím.
Na *nováčky* to může mít naopak opačný efekt, kdy si řeknou: *Tyjo tenhle framework je ale bezpečnostní díra, když i na vlastním webu mají zaplé debugovací nástroje.*
Chápu trolling uživatelů, nicméně na celém webu je to nemístné. Nemluvě o tom, že to vlastně ani nefunguje jak má (chybí javascript) .
