### ISSUE TITLE
Route::$defaultFlags deprecated

### ISSUE THREAD

**Issue by JanGalek** [nette/web-content#446]
Route::$defaultFlags are deprecated - https://github.com/nette/application/commit/e04c0e169682d82033b83e8f88001ef9a0e4a372

How I can use now ?

**Comment by dg** [comment]
This is not support forum https://forum.nette.org/cs/26357-route-secured-a-defaultflags-v-https-pod-nette-2-4

**Comment by Myiyk** [comment]
But in documentation is $defaultFlags used 3x in czech version and 2x in english
https://github.com/nette/web-content/blob/doc-2.4/cs/routing.texy#L323

**Comment by dg** [comment]
There is no stable Nette and branch 2.4 is currently identical copy of 2.3.
