### ISSUE TITLE
Better chapter navigation

### ISSUE THREAD

**Issue by hrach** [nette/web-content#45]
Each page has some next & previous chapter navigation. The order is parsed from homepage. However, the next chapter name is parsed as the link value. The best would be show the title of the next chapter. This is significant for chapters, which are somehow connected in one `<li>` item on doc homepage.

Examples:
- http://doc.nette.org/en/2.1/validators
  - next chapter title now: strings
  - next chapter title parsed: String Processing – Nette\Utils\Strings
- http://doc.nette.org/en/2.1/database-table
  - next chapter title now: Selection
  - next chapter title parsed: Database: Selection

**Comment by klimesf** [comment]
I believe this can be closed now.

**Comment by hrach** [comment]
when it was fixed? :)
