### ISSUE TITLE
Chybí requirements checker

### ISSUE THREAD

**Issue by kucix** [nette/web-content#463]
https://doc.nette.org/cs/2.4/requirements
Na stránce je zmiňován requirements checker ke stažení v balíčku nette...

V adresáři tools je jen open-in-editor

**Comment by dg** [comment]
Can you send PR?

**Comment by kucix** [comment]
I don't know where requirements checker is.
I can found him only in 2.3 branch (an older), but i don't know where is for 2.4 branch.
Maybe is not issue for web-content, but for nette itself.

**Comment by dg** [comment]
It is now in Sandbox https://github.com/nette/sandbox/tree/master/www/checker
